services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "3001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  s3:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
    ports:
      - "3002:9000"
      - "3003:9001"
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - s3
volumes:
  pgdata:
    driver: local
  miniodata:
    driver: local
